# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        appname: DRIMS
        instanceId: DRIMS:${spring.application.instance_id:${random.value}}

ribbon:
    eureka:
        enabled: true

zuul:
    routes:
          wind:
              url: https://swim.iblsoft.com/wxmaps?SERVICE=WMS&VERSION=1.3.0
          geoserver:
              url: http://geoserver.dreams.svc.cluster.local:8080/geoserver              
    host:
        connect-timeout-millis: 40000
        socket-timeout-millis: 40000


# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 40000

management:
    context-path: /management
    security:
       enabled: false
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
endpoints:
   health:
     sensitive: true

spring:
    application:
        name: DRIMS
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors: #By default CORS are not enabled. Uncomment to enable.
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    mail:
        from: DRIMS@localhost
    swagger:
        title: DRIMS API
        description: DRIMS API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
    ribbon:
        # comma seperated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev
