# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        prefer-ip-address: false
        hostname: flightservice.dreams.svc.cluster.local
    client:
        enabled: true
        healthcheck:
            enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://admin:admin@jhipster-registry.dreams.svc.cluster.local:8761/eureka/

spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    cloud:
        stream:
            kafka:
                binder:
                    brokers: kafka.dreams.svc.cluster.local
                    zk-nodes: kafka-zoo-svc.dreams.svc.cluster.local
            bindings:
                user-notifications:
                    binder: kafka
                    destination: user-notifications-topic
                    contentType: application/json
                    group: client-pushing-group
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://dreamsdb-postgresql.dreams.svc.cluster.local:5432/DRIMS-Flight
        name:
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
        database: POSTGRESQL
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: com.ids.drims.flight.config.hazelcast.HazelcastCacheRegionFactory
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
    data:
        elasticsearch:
            cluster-name: dreams-cluster
            cluster-nodes: elasticsearch-discovery.dreams.svc.cluster.local:9300
    mail:
        host: smtp.gmail.com
        port: 587
        username: dreams.notify@gmail.com  #Replace this field with your Gmail username.
        password: IdsDreams          #Replace this field with your Gmail password.
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
    thymeleaf:
        cache: true

liquibase:
    contexts: prod

server:
    port: 8090
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        hazelcast:
            backupCount: 1
    security:
        client-authorization:
            accessTokenUri: http://uaaservice/oauth/token
            tokenServiceId: uaaservice
            clientId: internal
            clientSecret: internal
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: FlightService@localhost
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: FlightService
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
        spectator-metrics: # Reports Spectator Circuit Breaker metrics in the logs
            enabled: false
            # edit spring.metrics.export.delay-millis to set report frequency

# ===================================================================
# Trac specific properties
# ===================================================================
trac:
   user: admin
   password: admin
   host: traccar-server.dreams.svc.cluster.local
   port: 8082
   apiUrl: /api
   wsUrl: /api/socket
 
# ===================================================================
# Tracks Purge specific properties
# ===================================================================

tracksPurge:
   cronSchedul: "0 0 00 * * *" # every day at time 00:00 "0 0 00 * * *"
   numMonths: -6 # -n months
